version: '3.3'
services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: home_project
            MYSQL_USER: home
            MYSQL_PASSWORD: home
            MYSQL_ROOT_PASSWORD: home
        ports:
            - 3306:3306
        volumes:
            - my-db:/var/lib/mysql
volumes:
    my-db: