version: "3"
services:
    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: home
            ME_CONFIG_BASICAUTH_PASSWORD: home
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: home
            ME_CONFIG_MONGODB_ADMINPASSWORD: home
        links:
            - mongo
        networks:
            - mongo-compose-network
    mongo:
        image: mongo
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: home
            MONGO_INITDB_ROOT_PASSWORD: home
        volumes:
            - /home/$USER/workspace/
        networks:
            - mongo-compose-network

networks:
    mongo-compose-network:
        driver: bridge