server:
  port: 8090

spring:
  application:
    name: home-project
  data:
    mongodb:
      authentication-database: admin
      username: home
      password: home
      database: home-project
      port: 27017
      host: localhost