server:
  port: 8090

spring:
  application:
    name: home-project
  datasource:
    url: jdbc:mysql://localhost:3306/home_project
    username: home
    password: home
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true